module.exports.CityController = require('./city.controller')
module.exports.AreaController = require('./area.controller')
module.exports.UserController = require('./user.controller')
module.exports.AuthController = require('./auth.controller')
module.exports.VehicleController = require('./vehicle.controller')
module.exports.CategoryController = require('./category.controller')
module.exports.feedbackController = require('./feedback.controller')
module.exports.loginHistoryController = require('./loginHistory.controller')